### ISSUE TITLE
Release the newest versions

### ISSUE THREAD

**Issue by ranolfi** [pawitp/libva-mesa-driver-vlc#1]
Hey, first of all thanks for your work.

It seems the most up-to-date versions have been successfully built. Can you make them available for download?

Regards

**Comment by pawitp** [comment]
I've added a release build so it should be automatically uploaded now: https://github.com/pawitp/libva-mesa-driver-vlc/releases/tag/20.0.7-3

**Comment by ranolfi** [comment]
Ok, thanks. Now, it seems the version tagged [`20.0.1-1`](https://github.com/pawitp/libva-mesa-driver-vlc/releases/tag/20.0.1-1) should actually be `20.1.1-1`, no?

**Comment by pawitp** [comment]
Fixed
